services:
  mysql-db-inventory:
    image: mariadb:10.6
    container_name: mysql-db-inventory
    restart: always
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: inventory-db
      MYSQL_USER: lakbir
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
    - 9999:80
    environment:
      PMA_HOST: mysql-db-inventory
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - '8098:8098'
    expose:
      - '8098'
    restart: always
    depends_on:
      mysql-db-inventory:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://mysql-db-inventory:3306/inventory-db
  postgres-service:
    image: postgres
    container_name: postgres-service
    volumes:
      - postgres_data_s:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: k1234
    ports:
      - '5432:5432'
    expose:
      - '5432'
    healthcheck:
      test: "exit 0"
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    expose:
      - "8888"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-med@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-1234}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-service:5432/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: k1234
      KEYCLOAK_ADMIN: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      postgres-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/auth/realms/master" ]
      interval: 60s
      timeout: 20s
      retries: 25
  customer-thymeleaf-service:
    build: ./customer-front-thymeleaf-app
    container_name: customer-thymeleaf-service
    ports:
      - '8090:8090'
    expose:
      - '8090'
    restart: always
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      - KEYCLOAK_REDIRECT_URI=http://localhost:8090/login/oauth2/code/sdia-customer-client
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/sdia-realm
      - KEYCLOAK_AUTH=http://localhost:8080/realms/sdia-realm/protocol/openid-connect/auth
      - KEYCLOAK_AUTH_TOKEN=http://localhost:8080/realms/sdia-realm/protocol/openid-connect/token
  angular-front:
    build: ./customer-front-angular-app
    container_name: angular-front
    ports:
      - '8085:80'
    expose:
      - '8085'
    restart: always
volumes:
  mysql_data:
  postgres_data_s:
  pgadmin_data: